PUBLISHER_TYPE = 'publisher'
SUBSCRIBER_TYPE = 'subscriber'

USER_TYPES = [PUBLISHER_TYPE, SUBSCRIBER_TYPE]

LIST_TOPICS_ACTION = 'list_topics'
ERROR_MSG_ACTION = 'error'
SUCCESS_MSG_ACTION = 'success'
BROADCAST_MSG_ACTION = 'broadcast'
UNREAD_MSG_ACTION = 'unread'